### ISSUE TITLE
Converting shapely polygons to coordinates

### ISSUE THREAD

**Issue by pakiessling** [jadexq/ELLA#1]
Congratulations on the preprint.

I am very interested in subcellular analysis and ELLA looks very cool.

Like most of your users I have my segmented cells as shapely formats in a geopandas .parquet.

Do you have a recommendation how to best bring them into the format required by ELLA?

Thank you!

**Comment by jadexq** [comment]
Thank you very much for your interest in ELLA! And thank you for bringing up this important issue! In brief, we can load `.parquet` using pandas, then the cell segmentations become a data frame with three columns: `cell_id`, `vertex.x`, `vertex.y` -- this is the format that ELLA takes (where each row corresponds to a point on the segmentation polygon). However, if there're too few points (like if only the vertex points are included), we may need to do interpolation to add more (non-vertex) points to facilitate ELLA's cell registration. For the details and the code, I created a notebook [here](https://github.com/jadexq/ELLA/blob/main/issues/process_geopandas_parquet_segmentation.ipynb) using the 10x Xenium's `.parquet`. Just let me know if you have any questions or suggestions! Thank you!

**Comment by pakiessling** [comment]
Thank you. I am excited to give it a spin.
Another question that came to my mind:
I would be very interested to compare RNA patterns between treatments/ disease groups.
Do you think one could perform a statistical test between ELLA results from multiple samples?

**Comment by jadexq** [comment]
This can be a very exciting application of ELLA! Yes, and there are a few ways to do it depending on the biological/biomedical problem of interest. For example, (a) if you focus on one gene and want to see if its pattern(s) is(are) the same/different across samples, and if your ST data comes with a good throughput (like at least several counts of the gene per one cell), you can obtain its expression pattern cluster label (categorical valued) and the expression pattern score (continues valued) in each cell by applying ELLA to one cell at a time. Then you may pool the labels/scores of cells in each sample respectively, and perform statistical tests across samples. (b) If you focus on one gene but the throughput is not good (like only one or two counts per cell), you may consider applying ELLA to multiple cells at a time to boot power. You may apply ELLA to all cells across all the samples to obtain the likelihood of merged samples, and to cells in each sample to obtain the likelihood and the estimated expression pattern of a particular sample, then a likelihood ratio test can potentially be used to provide statistical significance. (c) If you have a group of genes, similar to (a), you can apply ELLA to cells in each sample across genes, and perform tests using the ELLA labels/scores (across genes) between/among samples. Again, this is a very interesting application and let us know if you'd like to discuss more! Thank you!

**Comment by pakiessling** [comment]
Very cool. Thank you!
I might get in touch after a try a couple of things!

**Comment by jadexq** [comment]
Sure! Thank you!
